In [2]:
import numpy as np

In [7]:

# 1. Create a null vector of size 10 but the fifth value which is 1.
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
# Create a vector with values ranging from 10 to 49.
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
#Create a 3x3 matrix with values ranging from 0 to 8
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
a=np.array([1,2,0,0,4,0])
print("index where element is zero is ",np.where(a>0))


index where element is zero is  (array([0, 1, 4], dtype=int64),)


In [30]:
# Create a 10x10 array with random values and find the minimum and maximum values
a=np.random.randint(0,100,(10,10))
print(a)
print("minimumm of array is ", a.min())
print("max of array is ", a.max())

[[ 7 22 50 89 76 11 43 95  5  6]
 [ 5  4 49 70 22 73 61 39 28 71]
 [22 90 99 34 91 51 16  9 29 96]
 [ 2 42 53 91 40 40 55 48 99 86]
 [20  6 96  8 41 87  0 16 94 44]
 [91 31 77 48 28 88 42 72 13 67]
 [80 34 95 11 38 63 13 21 60 37]
 [22 34 18 80 20  8 59 50 47 60]
 [23 15 10 59 72 56 18 81 77 16]
 [ 9 60 80 69 78 60 64 56 77 74]]
minimumm of array is  0
max of array is  99


In [44]:
# Create a random vector of size 30 and find the mean value.
a=np.random.rand(30)
print("Mean of above vector is " , a.mean())

Mean of above vector is  0.4980196089769867
